/** Écrans ChargeAir montrés sur le site, et le texte anglais de chacun (clé : texte français exact de la maquette). */
export const ecrans = ['Main', 'Reservation', 'Session', 'FinSession', 'Borne', 'Hote'];

export const dictionnaire = {
  // Main
  'ChargeAir': 'ChargeAir',
  'LM': 'LM',
  'Vertou, Loire-Atlantique': 'Vertou, Loire-Atlantique',
  'Ce soir · 20:00 → 07:00 · Renault Zoé': 'Tonight · 20:00 → 07:00 · Renault Zoé',
  'Compatible Zoé': 'Zoé compatible',
  '7 kW et plus': '7 kW and up',
  'Accès libre': 'Self-access',
  '3 km': '3 km',
  '2,40 &euro;/h': '&euro;2.40/h',
  '1,90 &euro;/h': '&euro;1.90/h',
  '3,10 &euro;/h': '&euro;3.10/h',
  '2,20 &euro;/h': '&euro;2.20/h',
  '14 bornes ce soir': '14 chargers tonight',
  'Les plus proches': 'Nearest first',
  'Chez Camille': "Camille's place",
  '1,2 km &middot; 4 min en voiture': '1.2 km &middot; 4 min by car',
  '7,4 kW': '7.4 kW',
  'Type 2': 'Type 2',
  '(37 avis)': '(37 reviews)',
  'Chez Karim': "Karim's place",
  '2,4 km &middot; 7 min en voiture': '2.4 km &middot; 7 min by car',
  '3,7 kW': '3.7 kW',
  'Hôte présent': 'Host present',
  '(12 avis)': '(12 reviews)',
  'Chez Sylvie et Marc': "Sylvie and Marc's place",
  '2,9 km &middot; 8 min en voiture': '2.9 km &middot; 8 min by car',
  'Rechercher': 'Search',
  'Réservations': 'Bookings',
  'Ma borne': 'My charger',
  'Profil': 'Profile',

  // Borne
  'Vertou (44) &middot; 1,2 km de vous &middot; Hôte depuis mars 2024': 'Vertou (44) &middot; 1.2 km away &middot; Host since March 2024',
  'Compatible avec votre Renault Zoé': 'Compatible with your Renault Zoé',
  "Prise Type 2, votre Zoé accepte 7,4 kW sur cette borne. Une charge de 20 % à 80 % prendrait environ":
    'Your Zoé accepts 7.4 kW through this Type 2 charger. A charge from 20% to 80% would take about',
  '4 h 20': '4h 20min',
  'et ajouterait': 'and add',
  '31 kWh': '31 kWh',
  ', soit à peu près 180 km.': ', or about 180 km.',
  'Puissance': 'Power',
  'Monophasé 32 A': 'Single-phase 32A',
  'Connecteur': 'Connector',
  'Câble attaché': 'Attached cable',
  'Emplacement': 'Location',
  'Allée privée': 'Private driveway',
  'Extérieur, éclairé': 'Outdoor, lit',
  'Présence': 'Presence',
  'Non requise': 'Not required',
  'Accès autonome': 'Self-access',
  'Comment vous accédez à la borne': 'How you access the charger',
  "Le code du portail vous est envoyé une heure avant votre créneau. Vous confirmez votre branchement depuis l'application : Camille est prévenue, elle n'a pas besoin d'être présente.":
    "The gate code is sent to you one hour before your slot. You confirm you're plugged in from the app — Camille is notified and doesn't need to be there.",
  '2,40 &euro;': '&euro;2.40',
  '/ heure': '/ hour',
  'soit environ 0,33 &euro;/kWh pour votre Zoé': 'about &euro;0.33/kWh for your Zoé',
  'Choisir un créneau': 'Choose a slot',

  // Reservation
  'Reserver chez Camille': 'Book with Camille',
  'Vertou &middot; 7,4 kW &middot; 2,40 &euro;/h': 'Vertou &middot; 7.4 kW &middot; &euro;2.40/h',
  'Quel jour ?': 'Which day?',
  'Mar': 'Tue',
  'Mer': 'Wed',
  'Jeu': 'Thu',
  'Ven': 'Fri',
  'Sam': 'Sat',
  'Dim': 'Sun',
  'Créneaux ouverts par Camille': 'Slots offered by Camille',
  '20:00 &rarr; 00:30': '20:00 &rarr; 00:30',
  "4 h 30 &middot; couvre votre charge jusqu'à 80 %": '4h 30min &middot; covers your charge to 80%',
  '10,80 &euro;': '&euro;10.80',
  '20:00 &rarr; 07:00': '20:00 &rarr; 07:00',
  '11 h &middot; nuit complète': '11h &middot; full night',
  '26,40 &euro;': '&euro;26.40',
  '00:30 &rarr; 07:00': '00:30 &rarr; 07:00',
  'Déjà réservé': 'Already booked',
  'Durée réservée': 'Booked duration',
  '4 h 30 &times; 2,40 &euro;/h': '4h 30min &times; &euro;2.40/h',
  'Frais de service ChargeAir': 'ChargeAir service fee',
  '1,60 &euro;': '&euro;1.60',
  'Total': 'Total',
  '12,40 &euro;': '&euro;12.40',
  'Environ': 'About',
  '0,40 &euro;/kWh': '&euro;0.40/kWh',
  '. Les mêmes 31 kWh vous coûteraient à peu près': '. The same 31 kWh would cost about',
  '21 &euro;': '&euro;21',
  'sur une borne rapide.': 'at a fast charger.',
  "Vous payez le créneau réservé, quelle que soit la durée réelle. Au-delà de 00:30, chaque heure entamée est facturée 3,60 &euro;, soit une majoration de 50 %.":
    'You pay for the slot you book, no matter the actual duration. Past 00:30, every extra hour is billed &euro;3.60 — a 50% markup.',
  'Réserver &middot; 12,40 &euro;': 'Book &middot; &euro;12.40',

  // Session
  'Charge en cours': 'Charging',
  'sur les 4 h 30 réservées &middot; fin à 00:30': 'of the 4h 30min booked &middot; ends at 00:30',
  'Branchement confirmé à 20:03, position vérifiée': 'Plugged in confirmed at 20:03, location verified',
  'Estimé': 'Estimated',
  'kWh ajoutés': 'kWh added',
  'Autonomie': 'Range',
  'km environ': 'est. km',
  'À payer': 'Due',
  '&euro; au total': '&euro; total',
  'Nous vous préviendrons vers': "We'll notify you around",
  '00 h 15': '00:15',
  ', quand votre Zoé devrait avoir atteint 80 %.': ', when your Zoé should reach 80%.',
  'C': 'C',
  'Camille R.': 'Camille R.',
  '12 rue des Vignes, Vertou': '12 rue des Vignes, Vertou',
  'Itinéraire': 'Directions',
  'Contacter': 'Contact',
  "Le créneau réservé vous est facturé quoi qu'il arrive. Débrancher plus tôt ne change rien&nbsp;; rester au-delà de 00:30 ajoute 3,60 &euro; par heure entamée.":
    "The booked slot is charged no matter what. Unplugging early changes nothing&nbsp;; staying past 00:30 adds &euro;3.60 per extra hour.",
  "J'ai débranché, terminer": 'Finish charging',
  'Un problème avec cette borne ?': 'Having trouble with this charger?',

  // FinSession
  'Charge terminée.': 'Charging complete.',
  "Merci d'être passée chez Camille.": "Thanks for stopping by Camille's.",
  'Durée réelle': 'Actual duration',
  '4 h 12 &middot; 20:03 &rarr; 00:15': '4h 12min &middot; 20:03 &rarr; 00:15',
  'Créneau facturé': 'Billed slot',
  '4 h 30': '4h 30min',
  'Énergie estimée': 'Estimated energy',
  'environ 31 kWh': 'about 31 kWh',
  'Visa &bull;&bull;&bull;&bull; 4242': 'Visa &bull;&bull;&bull;&bull; 4242',
  'Camille reçoit': 'Camille gets',
  '. Vous avez payé environ': '. You paid about',
  '9 &euro; de moins': '&euro;9 less',
  "qu'à une borne rapide.": 'than a fast charger.',
  'Comment s\'est passée la charge ?': 'How was the charge?',
  'Accès facile': 'Easy access',
  'Bien indiqué': 'Clearly marked',
  'Emplacement sûr': 'Safe location',
  'Accueil chaleureux': 'Warm welcome',
  'Un mot pour Camille (facultatif)': 'A note for Camille (optional)',
  'Nouveau badge : Habitué du quartier': 'New badge: Neighborhood regular',
  '5e charge chez le même hôte': '5th charge with the same host',
  'Envoyer mon avis': 'Send my review',
  'Reprogrammer une charge chez Camille': 'Book another charge with Camille',

  // Hote
  'Ouverte': 'Open',
  'Septembre 2026': 'September 2026',
  'Voir le détail': 'See details',
  '148 &euro;': '&euro;148',
  'sur 19 sessions': 'from 19 sessions',
  'Électricité estimée': 'Estimated electricity',
  'Gain net': 'Net earnings',
  '86 &euro;': '&euro;86',
  'Particulier vérifié': 'Verified host',
  'Identité et justificatif de domicile validés': 'ID and proof of address verified',
  'Prochaines réservations': 'Upcoming bookings',
  'Lucie M. &middot; Renault Zoé': 'Lucie M. &middot; Renault Zoé',
  'Ce soir 20:00 &rarr; 00:30 &middot; 5e visite': 'Tonight 20:00 &rarr; 00:30 &middot; 5th visit',
  'TD': 'TD',
  'Thomas D. &middot; Peugeot e-208': 'Thomas D. &middot; Peugeot e-208',
  'Samedi 09:00 &rarr; 14:00 &middot; 1re visite': 'Saturday 09:00 &rarr; 14:00 &middot; 1st visit',
  '12,00 &euro;': '&euro;12.00',
  'Mes disponibilités': 'My availability',
  'Modifier': 'Edit',
  '19:00 &rarr; 07:00': '19:00 &rarr; 07:00',
  'L': 'M',
  // Mardi puis mercredi : deux « M » dans l'ordre de la semaine.
  'M': ['T', 'W'],
  'J': 'T',
  'V': 'F',
  'S': 'S',
  'D': 'S',
  '09:00 &rarr; 18:00': '09:00 &rarr; 18:00',
  'Reservations': 'Bookings',
};
