/** Écrans Pil’Poil montrés sur le site, et le texte anglais de chacun (clé : texte français exact de la maquette). */
export const ecrans = ['Carte', 'Main', 'SignalementCouleurs', 'Correspondances', 'MiseEnRelation'];

export const dictionnaire = {
  // Main
  "Pil'Poil": "Pil'Poil",
  'Ensemble,': 'Together,',
  'ramenons-les à la maison.': "let's bring them home.",
  Commencer: 'Start',
  "J'ai perdu mon animal": 'I lost my pet',
  'Créer une alerte de recherche': 'Create a search alert',
  'Trouvés près de vous': 'Found near you',
  'Voir la carte': 'View map',
  'Chien errant,': 'Stray dog,',
  'collier rouge': 'red collar',
  'à 352 m · il y a 3 h': '352 m away · 3h ago',
  Recueilli: 'In care',
  'Chien noir aperçu': 'Black dog spotted',
  'près du canal': 'near the canal',
  'à 897 m · il y a 1 h': '897 m away · 1h ago',
  'Sur place': 'On site',
  'Chien gris, boite': 'Gray dog, limps',
  "d'une patte": 'on one paw',
  'à 2,1 km · il y a 2 j': '2.1 km away · 2d ago',
  Accueil: 'Home',
  Carte: 'Map',
  'Mes animaux': 'My pets',
  Profil: 'Profile',

  // SignalementCouleurs
  Fermer: 'Close',
  'Signaler un animal trouvé': 'Report a found pet',
  "L'animal": 'Pet',
  'Étape 1 sur 2': 'Step 1 of 2',
  Photo: 'Photo',
  Ajouter: 'Add',
  'Une photo permet au propriétaire de reconnaître son animal tout de suite.':
    'A photo helps the owner recognize their pet right away.',
  Espèce: 'Species',
  Chien: 'Dog',
  Chat: 'Cat',
  Race: 'Breed',
  'Je ne sais pas': "I don't know",
  Genre: 'Sex',
  Mâle: 'Male',
  Femelle: 'Female',
  Couleurs: 'Colors',
  Noir: 'Black',
  Blanc: 'White',
  Marron: 'Brown',
  Gris: 'Gray',
  Roux: 'Red',
  Tacheté: 'Spotted',
  Autre: 'Other',

  // Carte
  'Autour de moi': 'Around me',
  Paris: 'Paris',
  'Ville, quartier, adresse': 'City, neighborhood, address',
  '1 chien trouvé': '1 dog found',
  '5 km': '5 km',
  Filtrer: 'Filter',

  // Correspondances
  Correspondances: 'Matches',
  'Animaux trouvés qui pourraient être Balto.': 'Found pets that could be Balto.',
  'Ressemblance forte': 'Strong match',
  'Chien errant, collier rouge': 'Stray dog, red collar',
  '75004 Paris': '75004 Paris',
  'Ressemblance possible': 'Possible match',
  'Berger allemand trouvé devant la gare': 'German shepherd found outside the station',
  '75010 Paris': '75010 Paris',
  'À vérifier': 'To verify',
  'Chien noir aperçu près du canal': 'Black dog near the canal',
  'Petit chien sans collier': 'Small dog, no collar',
  '75011 Paris': '75011 Paris',

  // MiseEnRelation
  'Mise en relation': 'Contact request',
  'Vous · Sollicité': 'You · Requested',
  'Quelqu\'un pense avoir trouvé son animal': "Someone thinks it's their pet",
  'Demande reçue il y a 2 minutes': 'Request received 2 minutes ago',
  'En acceptant, vous partagez vos coordonnées avec cette personne. Vous ne recevez pas les siennes.':
    "By accepting, you share your contact details. You won't receive theirs.",
  Téléphone: 'Phone',
  'E-mail': 'Email',
  'Chien beige, oreilles tombantes': 'Beige dog, floppy ears',
  'Paris · il y a 6 h': 'Paris · 6h ago',
  'Ce que la personne voit': 'What the person sees',
  "Quelqu'un pense que l'animal que vous avez signalé est le sien.": 'Someone thinks the pet you reported is theirs.',
  Accepter: 'Accept',
  Refuser: 'Decline',
  'Une demande ne peut être acceptée ou refusée qu\'une seule fois.': 'A request can only be accepted or declined once.',
};
