/** Écrans Teamago montrés sur le site, et le texte anglais de chacun (clé : texte français exact de la maquette). */
export const ecrans = ['Participants', 'Decompte', 'Infos', 'Reglement'];

export const dictionnaire = {
  // Lieux, adresses, noms (inchangés dans les deux langues)
  'Le Lioran': 'Le Lioran',
  'Station du Lioran · 15300 Laveissière': 'Station du Lioran · 15300 Laveissière',
  'Parking du stade': 'Parking du stade',
  '12 av. de la Gare · 15000 Aurillac': '12 av. de la Gare · 15000 Aurillac',
  '700 km': '700 km',
  'Petit Lucas': 'Petit Lucas',
  'Bernard Nathan': 'Bernard Nathan',
  'Moreau Théo': 'Moreau Théo',
  'Girard Enzo': 'Girard Enzo',
  'Martin Julien': 'Martin Julien',
  'Fontaine Louis': 'Fontaine Louis',
  'Rousseau Adam': 'Rousseau Adam',
  'Garnier Paul': 'Garnier Paul',
  'Lucas, Nathan, Théo, Enzo': 'Lucas, Nathan, Théo, Enzo',
  PL: 'PL',
  BN: 'BN',
  MT: 'MT',
  GE: 'GE',
  MJ: 'MJ',
  FL: 'FL',
  RA: 'RA',
  GP: 'GP',

  // Participants
  Participants: 'Participants',
  'Tous · 8': 'All · 8',
  'Voyageurs · 8': 'Travelers · 8',
  'Conducteurs · 1': 'Drivers · 1',
  'Joueur · Voyageur': 'Player · Traveler',
  'Conducteur · Berline': 'Driver · Sedan',
  'Ajouter un participant': 'Add a participant',
  'Reprendre le dernier déplacement': 'Reuse last trip',

  // Décompte
  Décompte: 'Breakdown',
  'Ça boucle': 'It balances',
  'Les participations couvrent exactement les frais.': 'Contributions cover the costs exactly.',
  'Ce que coûte le déplacement': 'What the trip costs',
  'Frais kilométriques · 700 km': 'Mileage · 700 km',
  Péages: 'Tolls',
  'Location du minibus': 'Minibus rental',
  'Hôtel · 8 pers. × 1 nuit': 'Hotel · 8 people × 1 night',
  'Inscription · Repas · Autres': 'Registration · Meals · Other',
  'Total réparti': 'Total split',
  'Assiette trajet 389,00 €': 'Trip base €389.00',
  '÷ 8 parts voyageur': '÷ 8 traveler shares',
  'Réparti au centime : 4 parts à 48,63 €, 4 parts à 48,62 €.':
    'Split to the cent: 4 shares at €48.63, 4 shares at €48.62.',
  'Où va l’argent': 'Where the money goes',
  'Encaissé auprès des participants': 'Collected from participants',
  'Remboursé aux conducteurs': 'Reimbursed to drivers',
  'Avancé par l’association': 'Advanced by the club',
  'Solde association': 'Club balance',

  // Infos (nouveau déplacement)
  Annuler: 'Cancel',
  'Nouveau déplacement': 'New trip',
  'Où va-t-on ?': 'Where are we going?',
  Destination: 'Destination',
  'Point de rendez-vous': 'Meeting point',
  'Calculé automatiquement': 'Calculated automatically',
  'aller-retour': 'round trip',
  '5 h 10': '5 h 10 min',
  'sans pause': 'non-stop',
  péages: 'tolls',
  'Distance et durée calculées sur l’itinéraire. Le péage est repris du dernier trajet identique — corrige-le au ticket réel.':
    'Distance and duration are calculated from the route. The toll is copied from the last identical trip — correct it against the actual receipt.',
  'Quand ?': 'When?',
  Date: 'Date',
  'sam. 21 nov. 2026': 'Sat, Nov 21, 2026',
  Départ: 'Departure',
  'Créer le déplacement': 'Create trip',

  // Règlement
  Règlement: 'Payments',
  centralisé: 'centralized',
  réglés: 'paid',
  'Reste à encaisser': 'Still to collect',
  'Déjà encaissé': 'Already collected',
  'À encaisser sur le compte de l’association': 'To collect into the club account',
  '4 déjà réglés': '4 already paid',
  '→ association': '→ club',
  'À rembourser par l’association': 'To be refunded by the club',
  'conducteur · km + péage avancés': 'driver · mileage + tolls advanced',
  'Envoyer les récapitulatifs': 'Send summaries',
};
